version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    healthcheck:
      test: pg_isready -U skymarket -d skymarket
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
    - "5432:5432"

  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "3000:3000"
    volumes:
      - ../skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ../skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

  migrations:
    build: ../skymarket/.
    env_file: ../skymarket/.env
    environment:
      DB_HOST: db
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  api:
    build: ../skymarket/.
    env_file: ../skymarket/.env
    environment:
      DB_HOST: db
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully

volumes:
  postgres_data:  
  frontend: